"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar, NavigationBar } from "@/components";
import localFont from 'next/font/local'
import { usePathname} from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

const globalSans = localFont({
  src: '../public/GeneralSans_Complete/Fonts/TTF/GeneralSans-Variable.ttf',
  // weight: `['100','200','400','500', '600', '700', '800']`,
  variable: '--font-gsans',
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const requiredPath = pathname?.split("/")[1];
  
  return (
    <html lang="en">
      <body className={`${globalSans.variable} font-gsans max-h-screen overflow-y-scroll`}>
        <NavBar/>
        { requiredPath && requiredPath === 'jobs' &&  <NavigationBar/>}
          { children }
        </body>
    </html>
  );
}
